#!/bin/bash
#
# Copyright (c) 2013-2014 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#


###
###

ARGUEMENT=$1
SUB_BIN_PATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
ABSOLUTE_PATH=${SUB_BIN_PATH}/$(basename "${BASH_SOURCE[0]}")

if [ "$#" -lt "1" -o "$1" == "help" -o "$1" == "--help" -o "$1" == "-h" ]
then
    echo "usage:  ssh_instance user@instance[:net[:subnet]] [command]"
    echo ""
    echo "  e.g.  ssh_instance user@instance"
    echo "  e.g.  ssh_instance user@instance:2"
    echo "  e.g.  ssh_instance user@instance:2:1 cat /etc/build.info"
    echo ""
    exit 1
fi

shift

USER=`echo $ARGUEMENT | awk -F '@' '{print $1 }'`
INST_TEMP=`echo $ARGUEMENT | awk -F '@' '{print $2 }'`
INST=`echo $INST_TEMP | awk -F ':' '{print $1 }'`
NET=`echo $INST_TEMP | awk -F ':' '{print $2 }'`
SUBNET=`echo $INST_TEMP | awk -F ':' '{print $3 }'`

if [ "$INST" == "" ]
then
    INST=$USER
fi

if [ "$NET" == "" ]
then
    NET="1"
fi

if [ "$SUBNET" == "" ]
then
    SUBNET="1"
fi

echo "  INST=$INST"
echo "  USER=$USER"
echo "  NET=$NET"
echo "  SUBNET=$SUBNET"


PASSWD=`keyring get CGCS admin`
if [ "$PASSWD" == "" ]
then
    PASSWD="admin"
fi

source /etc/nova/openrc
NET2="\$$NET"
SUBNET2="\$$SUBNET"

NET_INFO=`nova --os_password $PASSWD list --all-tenants | grep " ${INST} " | awk -F \| ' { print $8 } ' | awk -F \; "{print ${NET2} }" | awk -F \, "{print ${SUBNET2} }" | tr -d ' '`
echo "  NET_INFO=$NET_INFO"

MY_HOST=`hostname`
echo "  MY_HOST=$MY_HOST"

VM_HOST=`nova --os_password $PASSWD list --fields name,OS-EXT-SRV-ATTR:instance_name,OS-EXT-SRV-ATTR:host,status,Networks --all-tenants 1 | grep " ${INST} " | awk -F \| '{print $5 }' | tr -d ' '`
echo "  VM_HOST=$VM_HOST"

IP=`echo $NET_INFO | awk -F = '{print $2 }'`
echo "  IP=$IP"

NET=`echo $NET_INFO | awk -F = '{print $1 }'`
echo "  NET=$NET"

NETID=`neutron --os_password $PASSWD net-list | grep ${NET} | awk '{print $2}'`
echo "  NETID=$NETID"

DHCP_HOST=`neutron --os_password $PASSWD dhcp-agent-list-hosting-net $NET | grep True | head -n 1 | awk -F \| '{print $3 }' | tr -d ' '`
echo "  DHCP_HOST=$DHCP_HOST"

if [ "$DHCP_HOST" == "$MY_HOST" ]
then
   echo "  Enter name space"
   echo "  Sudo passwd required..."
   sudo pwd
   NETNS=`sudo ip netns | grep ${NETID}`
   echo "  NETNS=$NETNS"

   # ssh-keygen -f "$HOME/.ssh/known_hosts" -R ${IP}
   # sudo ssh-keygen -f "/root/.ssh/known_hosts" -R ${IP}
   sudo mkdir -p /root/.ssh/
   sudo touch /root/.ssh/known_hosts
   sudo ssh-keygen -R ${IP} -f "/root/.ssh/known_hosts"
   echo sudo ip netns exec ${NETNS} ssh ${USER}@${IP} $@
   # sudo ip netns exec ${NETNS} ssh -o 'StrictHostKeyChecking no' ${USER}@${IP} $@
   # sudo ip netns exec ${NETNS} ssh -o 'StrictHostKeyChecking no' ${USER}@${IP} $@
   sudo ip netns exec ${NETNS} ssh -o 'GlobalKnownHostsFile=/dev/null' ${USER}@${IP} $@
else
   echo "  proxy"
   ssh -t $DHCP_HOST "$SUB_BIN_PATH/ssh_instance $USER@$INST $@"
fi
